apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api-gateway.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name:  {{ .name }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: NO_PROXY
              value: "{{ .Values.noProxy }}"
            - name: HTTP_PROXY
              value: "{{ .Values.proxy}}"
            - name: HTTPS_PROXY
              value: "{{ .Values.proxy }}"
            - name: DEBUG
              value: {{ .Values.debug | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          {{/* readinessProbe: */}}
          {{/*   httpGet: */}}
          {{/*     path: /readiness */}}
          {{/*     port: 8080 */}}
          {{/*   initialDelaySeconds: 3 */}}
          {{/*   periodSeconds: 3 */}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
