{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "streampipes.fullname" . }}-ingress
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "streampipes.ui.fullname" . }}
            port:
              number: {{ .Values.ui.service.port }}
      - path: /streampipes-backend(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "streampipes.backend.fullname" . }}
            port:
              number: {{ .Values.backend.service.port }}
  {{- if .Values.streampipes.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.streampipes.ingress.host }}
    secretName: {{ .Values.streampipes.ingress.tlsSecretName | default (printf "%s-tls" (include "streampipes.ui.fullname" .)) }}
  {{- end }}
{{- end }}
