{{- if not .Values.streampipes.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snippet.streampipes.secret.name" . }}
  labels:
    {{- include "streampipes.labels" . | nindent 4 }}
type: Opaque
data:
  sp-initial-admin-password: {{ ternary (randAlphaNum 10) .Values.streampipes.admin.password (empty .Values.streampipes.admin.password) | b64enc | quote }}
  sp-initial-client-secret: {{ ternary (randAlphaNum 35) .Values.streampipes.serviceUser.secret (empty .Values.streampipes.serviceUser.secret) | b64enc | quote }}
  sp-encryption-passcode:  {{ ternary (randAlphaNum 20) .Values.streampipes.encryption.passcode (empty .Values.streampipes.encryption.passcode) | b64enc | quote }}
---
{{- end }}
{{- if and (not .Values.couchdb.enabled) (not .Values.externalCouchdb.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streampipes.fullname" . }}-couchdb-external
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  adminUsername: {{ required "externalCouchdb.adminUsername is required if not couchdb.enabled and not externalCouchdb.existingSecret" .Values.externalCouchdb.adminUsername | b64enc | quote }}
  adminPassword: {{ required "externalCouchdb.adminPassword is required if not couchdb.enabled and not externalCouchdb.existingSecret" .Values.externalCouchdb.adminPassword | b64enc | quote }}
  cookieAuthSecret: {{ required "externalCouchdb.cookieAuthSecret is required if not couchdb.enabled and not externalCouchdb.existingSecret" .Values.externalCouchdb.cookieAuthSecret | b64enc | quote }}
  erlangCookie: {{ required "externalCouchdb.erlangCookie is required if not couchdb.enabled and not externalCouchdb.existingSecret" .Values.externalCouchdb.erlangCookie | b64enc | quote }}
---
{{- end }}
{{- if and (not .Values.influxdb.enabled) (not .Values.externalInfluxdb.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streampipes.fullname" . }}-influxdb-external
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  sp-influxdb-admin-user-password: {{ ternary (randAlphaNum 20) .Values.externalInfluxdb.admin.password (empty .Values.externalInfluxdb.admin.token) | b64enc | quote }}
  sp-influxdb-admin-token: {{ ternary (randAlphaNum 20) .Values.externalInfluxdb.admin.token (empty .Values.externalInfluxdb.admin.token) | b64enc | quote }}
{{- end}}

