{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "streampipes.serviceAccountName" . }}
  labels:
    {{- include "streampipes.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4}}
    {{- end }}
  {{- end }}
{{- end }}
