apiVersion: v1
kind: Service
metadata:
  name: {{ include "streampipes.extensions.iiot.fullname" . }}
  labels:
    {{- include "streampipes.extensions.iiot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.extensions.iiot.service.type }}
  selector:
    {{ include "streampipes.extensions.iiot.selectorLabels" . | nindent 4 }}
  ports:
    - name: main
      protocol: TCP
      port: {{ .Values.extensions.iiot.service.port }}
      targetPort: {{ .Values.extensions.iiot.containerPort }}
  
  
