apiVersion: v1
kind: Service
metadata:
  name: {{ include "streampipes.backend.fullname" . }}
  labels:
    {{- include "streampipes.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "streampipes.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: main
      protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.containerPort }}
      
  
  
