apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app.kubernetes.io/component: backend
    {{- include "iotgo-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      {{- include "iotgo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend
        {{- include "iotgo-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: RUNMODE
              value: {{ .Values.backend.env.RUNMODE | quote }}
            - name: DB_HOST
              value: {{ .Values.backend.env.DB_HOST | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.dbSecretName }}
                  key: {{ .Values.backend.env.DB_USER_KEY }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.dbSecretName }}
                  key: {{ .Values.backend.env.DB_PASSWORD_KEY }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.dbSecretName }}
                  key: {{ .Values.backend.env.DB_NAME_KEY }}
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.dbSecretName }}
                  key: {{ .Values.backend.env.DB_PORT_KEY }}
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.appSecretName }}
                  key: SESSION_SECRET
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.appSecretName }}
                  key: JWT_SECRET_KEY
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
