apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.dbSecretName }}
type: Opaque
data:
  # Base64 encoded values for your PostgreSQL connection
  # Example: echo -n "postgres" | base64
  DB_USER: "" # <<-- REPLACE with base64 encoded PostgreSQL username (e.g., 'postgres')
  DB_PASSWORD: "" # <<-- REPLACE with base64 encoded PostgreSQL password (e.g., 'postgres')
  DB_NAME: "" # <<-- REPLACE with base64 encoded PostgreSQL database name (e.g., 'iotgo')
  DB_PORT: "" # <<-- REPLACE with base64 encoded PostgreSQL port (e.g., '5432')

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.appSecretName }}
type: Opaque
data:
  # Base64 encoded values for your application secrets
  # Example: echo -n "your-secure-session-secret" | base64
  SESSION_SECRET: "" # <<-- REPLACE with base64 encoded secret for session encryption
  JWT_SECRET_KEY: "" # <<-- REPLACE with base64 encoded secret for JWT signing
